# Generated by Django 4.2.7 on 2024-11-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave única de la configuración', max_length=100, unique=True)),
                ('valor', models.TextField(help_text='Valor de la configuración')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la configuración', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['clave'],
            },
        ),
    ]
